### ISSUE TITLE
Feature request: option to move/delete poster/background when no media file exists

### ISSUE THREAD

**Issue by edrock200** [RatingPosterDB/rpdb-folders#40] opened 2022-01-08 17:52 UTC
Me again. :)
Feature request for your consideration. We often reorg our media. E.g. move ended shows or old movies to an archive folder. Unfortunately *arrs don't send connect triggers on move. Rpdb has a feature to skip folders without media. But would be nice to have a feature to delete or move *.jpg to a quarantine folder in that same scenario so we aren't left with folders with just poster/background.jpg left behind.

Thanks for your consideration. 
Ed

**Comment by jaruba** [comment] 2022-01-09 01:10
@edrock200 what do you mean by "quarantine folder"? posters are not viruses 😄 

i'm not entirely sure of the feature expectation either, do you want a setting that just removes the poster / background files if it can't find any video file in the folder anymore during a full scan?

**Comment by edrock200** [comment] 2022-01-09 19:43
Lol maybe quarantine is the wrong term. If a folder is found without a media file (mkv, MP4, etc) then rpdb removes the poster.jpg and background.jpg, or moves the folder to a "recycle bin" folder if-you-will. Unfortunately the arrs are great about cleaning up items it didn't create when you move a show or movie.

**Comment by jaruba** [comment] 2022-01-11 18:59
@edrock200 What if i add support for the events from radarr / sonarr that handle moving / removing media?

That way when moving videos with radarr / sonarr, it will also move the poster / backgrounds, and when removing videos, it will remove the poster / backgrounds.

Does that sound like an acceptable solution?

**Comment by jaruba** [comment] 2022-01-16 02:41
@edrock200 

I just tested both Radarr (v3.2.2.5080) and Sonarr (v3.0.6.1342) and I was surprised to see that both moving media as well as deleting media is handled very well by both of these apps. When moving media through the apps they both moved the poster and background files too and removed their old folder, when deleting media through the apps they both also deleted the poster and background files and removed the folder also.

TBH, I don't think anything can be done from RPDB Folder's side to improve this behavior. If these apps didn't act the same way in ur case, then maybe you changed some setting?

**Comment by jaruba** [comment] 2022-01-17 00:40
I'm closing this issue due to not being able to reproduce it, if you consider it should be opened again you can do so.

**Closed by jaruba** 2022-01-17 00:40 UTC
